In [1]:
import pandas as pd

In [10]:
df = pd.read_csv("../data/raw/netflix_titles.csv")

In [11]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [12]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [13]:
df.shape

(7787, 12)

In [14]:
df.columns.tolist()

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description']

In [15]:
df.dtypes

show_id           str
type              str
title             str
director          str
cast              str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
description       str
dtype: object

In [16]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   str
 1   type          7787 non-null   str
 2   title         7787 non-null   str
 3   director      5398 non-null   str
 4   cast          7069 non-null   str
 5   country       7280 non-null   str
 6   date_added    7777 non-null   str
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   str
 9   duration      7787 non-null   str
 10  listed_in     7787 non-null   str
 11  description   7787 non-null   str
dtypes: int64(1), str(11)
memory usage: 730.2 KB

In [20]:
df.describe(include="object")

C:\Users\shiva\AppData\Local\Temp\ipykernel_5220\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,7787,7787,7787,5398,7069,7280,7777,7780,7787,7787,7787
unique,7787,2,7787,4049,6831,681,1565,14,216,492,7769
top,s1,Movie,3%,"Raúl Campos, Jan Suter",David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,Documentaries,Multiple women report their husbands as missin...
freq,1,5377,1,18,18,2555,118,2863,1608,334,3

In [21]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

director        30.679337
cast             9.220496
country          6.510851
date_added       0.128419
rating           0.089893
title            0.000000
show_id          0.000000
type             0.000000
release_year     0.000000
duration         0.000000
listed_in        0.000000
description      0.000000
dtype: float64

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.describe()

       release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

In [24]:
df.describe(include="object")

C:\Users\shiva\AppData\Local\Temp\ipykernel_5220\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,7787,7787,7787,5398,7069,7280,7777,7780,7787,7787,7787
unique,7787,2,7787,4049,6831,681,1565,14,216,492,7769
top,s1,Movie,3%,"Raúl Campos, Jan Suter",David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,Documentaries,Multiple women report their husbands as missin...
freq,1,5377,1,18,18,2555,118,2863,1608,334,3

In [25]:
df.shape
df.dtypes
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [26]:
missing = df.isnull().sum()

print(missing[missing > 0])

director      2389
cast           718
country        507
date_added      10
rating           7
dtype: int64

In [27]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print(missing_percentage[missing_percentage > 0].sort_values(ascending=False))

director      30.679337
cast           9.220496
country        6.510851
date_added     0.128419
rating         0.089893
dtype: float64

In [28]:
df['type'].value_counts()

type
Movie      5377
TV Show    2410
Name: count, dtype: int64

In [29]:
df['rating'].value_counts(dropna=False)

rating
TV-MA       2863
TV-14       1931
TV-PG        806
R            665
PG-13        386
TV-Y         280
TV-Y7        271
PG           247
TV-G         194
NR            84
G             39
NaN            7
TV-Y7-FV       6
UR             5
NC-17          3
Name: count, dtype: int64

In [30]:
df['release_year'].describe()

count    7787.000000
mean     2013.932580
std         8.757395
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2018.000000
max      2021.000000
Name: release_year, dtype: float64

In [31]:
df['country'].value_counts().head(15)

country
United States     2555
India              923
United Kingdom     397
Japan              226
South Korea        183
Canada             177
Spain              134
France             115
Egypt              101
Mexico             100
Turkey             100
Australia           83
Taiwan              78
Brazil              72
Philippines         71
Name: count, dtype: int64

In [32]:
df['director'].value_counts().head(10)

director
Raúl Campos, Jan Suter    18
Marcus Raboy              16
Jay Karas                 14
Cathy Garcia-Molina       13
Youssef Chahine           12
Martin Scorsese           12
Jay Chapman               12
Steven Spielberg          10
David Dhawan               9
Kunle Afolayan             8
Name: count, dtype: int64

In [33]:
df['show_id'].nunique(), len(df)

(7787, 7787)

In [34]:
df['type'].value_counts()

type
Movie      5377
TV Show    2410
Name: count, dtype: int64

In [35]:
df['rating'].value_counts(dropna=False)

rating
TV-MA       2863
TV-14       1931
TV-PG        806
R            665
PG-13        386
TV-Y         280
TV-Y7        271
PG           247
TV-G         194
NR            84
G             39
NaN            7
TV-Y7-FV       6
UR             5
NC-17          3
Name: count, dtype: int64

In [36]:
df['release_year'].describe()

count    7787.000000
mean     2013.932580
std         8.757395
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2018.000000
max      2021.000000
Name: release_year, dtype: float64

In [37]:
df['country'].value_counts().head(15)

country
United States     2555
India              923
United Kingdom     397
Japan              226
South Korea        183
Canada             177
Spain              134
France             115
Egypt              101
Mexico             100
Turkey             100
Australia           83
Taiwan              78
Brazil              72
Philippines         71
Name: count, dtype: int64

In [38]:
df['listed_in'].value_counts().head(15)

listed_in
Documentaries                                       334
Stand-Up Comedy                                     321
Dramas, International Movies                        320
Comedies, Dramas, International Movies              243
Dramas, Independent Movies, International Movies    215
Kids' TV                                            205
Children & Family Movies                            177
Documentaries, International Movies                 172
Children & Family Movies, Comedies                  169
Comedies, International Movies                      161
Dramas, International Movies, Romantic Movies       153
Comedies, International Movies, Romantic Movies     139
Dramas                                              117
Action & Adventure, Dramas, International Movies    117
International TV Shows, TV Dramas                   111
Name: count, dtype: int64

In [39]:
df['director'].value_counts().head(10)

director
Raúl Campos, Jan Suter    18
Marcus Raboy              16
Jay Karas                 14
Cathy Garcia-Molina       13
Youssef Chahine           12
Martin Scorsese           12
Jay Chapman               12
Steven Spielberg          10
David Dhawan               9
Kunle Afolayan             8
Name: count, dtype: int64

In [40]:
df_clean = df.copy()

In [41]:
df_clean.shape

(7787, 12)

In [42]:
df_clean['director'] = df_clean['director'].fillna('Not Specified')

In [43]:
df_clean['cast'] = df_clean['cast'].fillna('Not Specified')

In [44]:
df_clean['country'] = df_clean['country'].fillna('Not Specified')

In [45]:
df_clean['rating'] = df_clean['rating'].fillna('Not Rated')

In [46]:
df_clean.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           0
duration         0
listed_in        0
description      0
dtype: int64

In [47]:
df_clean['date_added'] = pd.to_datetime(
    df_clean['date_added'],
    errors='coerce'
)

In [48]:
df_clean['date_added'].dtype

dtype('<M8[us]')

In [51]:
df_clean['date_added'].isnull().sum()

np.int64(98)

In [52]:
print("Original missing dates:", df['date_added'].isnull().sum())
print("Cleaned missing dates:", df_clean['date_added'].isnull().sum())

Original missing dates: 10
Cleaned missing dates: 98

In [53]:
invalid_dates = df[
    df['date_added'].notna() &
    df_clean['date_added'].isna()
][['show_id', 'title', 'date_added']]

invalid_dates.head(20)

     show_id                        title          date_added
284     s285              Abnormal Summit      August 4, 2017
556     s557                     忍者ハットリくん   December 23, 2018
690     s691                Bad Education   December 15, 2018
819     s820  Being Mary Jane: The Series        July 1, 2017
902     s903     Big Dreams, Small Spaces       July 26, 2019
940     s941                       Bitten        May 26, 2016
1039   s1040                 Bondi Rescue    November 1, 2019
1048   s1049                   Borderline    December 2, 2017
1073   s1074                  Brain Games      March 15, 2019
1148   s1149                   Burnistoun     October 1, 2019
1291   s1292             Chasing Monsters   December 15, 2017
1300   s1301                       Cheers        July 1, 2017
1303   s1304             Chef & My Fridge      August 4, 2017
1315   s1316                  Chewing Gum       April 4, 2017
1472   s1473           Comedy Bang! Bang!   December 28, 2016
1577   s1578                   Dad's Army      March 31, 2018
1599   s1600              Dangerous Roads    February 1, 2019
1731   s1732                       Dexter     January 1, 2018
1943   s1944                     El Barco        July 1, 2017
1967   s1968                      El Vato   February 24, 2018

In [57]:
# Show the exact raw date values
print(df['date_added'].dropna().head(20).tolist())

['August 14, 2020', 'December 23, 2016', 'December 20, 2018', 'November 16, 2017', 'January 1, 2020', 'July 1, 2017', 'June 1, 2020', 'November 1, 2019', 'April 1, 2019', 'December 15, 2017', 'October 20, 2017', 'November 30, 2018', 'May 17, 2019', 'March 1, 2019', 'March 19, 2020', 'September 1, 2019', 'March 20, 2019', 'October 10, 2018', 'March 29, 2019', 'May 16, 2018']

In [58]:
# Show the Python data type of a date value
print(repr(df['date_added'].dropna().iloc[0]))
print(type(df['date_added'].dropna().iloc[0]))

'August 14, 2020'
<class 'str'>

In [59]:
# Count unique date formats/examples
print(df['date_added'].dropna().astype(str).str.strip().head(20).tolist())

['August 14, 2020', 'December 23, 2016', 'December 20, 2018', 'November 16, 2017', 'January 1, 2020', 'July 1, 2017', 'June 1, 2020', 'November 1, 2019', 'April 1, 2019', 'December 15, 2017', 'October 20, 2017', 'November 30, 2018', 'May 17, 2019', 'March 1, 2019', 'March 19, 2020', 'September 1, 2019', 'March 20, 2019', 'October 10, 2018', 'March 29, 2019', 'May 16, 2018']

In [60]:
df_clean['date_added'] = df['date_added'].copy()

In [61]:
df_clean['date_added'] = pd.to_datetime(
    df_clean['date_added'].str.strip(),
    format='mixed',
    errors='coerce'
)

In [62]:
print("Original missing dates:", df['date_added'].isnull().sum())
print("Cleaned missing dates:", df_clean['date_added'].isnull().sum())

Original missing dates: 10
Cleaned missing dates: 10

In [63]:
print(df_clean['date_added'].dtype)

datetime64[us]

In [64]:
print("Earliest date:", df_clean['date_added'].min())
print("Latest date:", df_clean['date_added'].max())

Earliest date: 2008-01-01 00:00:00
Latest date: 2021-01-16 00:00:00

In [65]:
df_clean[['show_id', 'title', 'date_added']].head(10)

  show_id  title date_added
0      s1     3% 2020-08-14
1      s2   7:19 2016-12-23
2      s3  23:59 2018-12-20
3      s4      9 2017-11-16
4      s5     21 2020-01-01
5      s6     46 2017-07-01
6      s7    122 2020-06-01
7      s8    187 2019-11-01
8      s9    706 2019-04-01
9     s10   1920 2017-12-15

In [66]:
df_clean['duration'].head(20)

0     4 Seasons
1        93 min
2        78 min
3        80 min
4       123 min
5      1 Season
6        95 min
7       119 min
8       118 min
9       143 min
10      103 min
11     1 Season
12     1 Season
13       89 min
14       91 min
15      149 min
16     1 Season
17      144 min
18      124 min
19       87 min
Name: duration, dtype: str

In [67]:
df_clean['duration'].value_counts().head(20)

duration
1 Season     1608
2 Seasons     382
3 Seasons     184
90 min        136
93 min        131
91 min        125
94 min        125
95 min        119
92 min        118
97 min        117
96 min        115
98 min        106
103 min       101
99 min        101
88 min        101
102 min        98
100 min        97
106 min        97
101 min        96
86 min         93
Name: count, dtype: int64

In [68]:
df_clean['duration'].dtype

In [69]:

df_clean['duration_minutes'] = (
    df_clean['duration']
    .str.extract(r'(\d+)\s*min')[0]
    .astype('Int64')
)

In [70]:
df_clean['duration_seasons'] = (
    df_clean['duration']
    .str.extract(r'(\d+)\s*Season')[0]
    .astype('Int64')
)

In [71]:
df_clean[['type', 'duration', 'duration_minutes', 'duration_seasons']].head(20)

       type   duration  duration_minutes  duration_seasons
0   TV Show  4 Seasons              <NA>                 4
1     Movie     93 min                93              <NA>
2     Movie     78 min                78              <NA>
3     Movie     80 min                80              <NA>
4     Movie    123 min               123              <NA>
5   TV Show   1 Season              <NA>                 1
6     Movie     95 min                95              <NA>
7     Movie    119 min               119              <NA>
8     Movie    118 min               118              <NA>
9     Movie    143 min               143              <NA>
10    Movie    103 min               103              <NA>
11  TV Show   1 Season              <NA>                 1
12  TV Show   1 Season              <NA>                 1
13    Movie     89 min                89              <NA>
14    Movie     91 min                91              <NA>
15    Movie    149 min               149              <NA>
16  TV Show   1 Season              <NA>                 1
17    Movie    144 min               144              <NA>
18    Movie    124 min               124              <NA>
19    Movie     87 min                87              <NA>

In [72]:
print("Movies:", (df_clean['type'] == 'Movie').sum())
print("Movies with duration in minutes:",
      df_clean.loc[df_clean['type'] == 'Movie', 'duration_minutes'].notna().sum())

print("TV Shows:", (df_clean['type'] == 'TV Show').sum())
print("TV Shows with seasons:",
      df_clean.loc[df_clean['type'] == 'TV Show', 'duration_seasons'].notna().sum())

Movies: 5377
Movies with duration in minutes: 5377
TV Shows: 2410
TV Shows with seasons: 2410

In [73]:
df_clean[['duration', 'duration_minutes', 'duration_seasons']].isnull().sum()

duration               0
duration_minutes    2410
duration_seasons    5377
dtype: int64

In [74]:
df_clean['country'].str.contains(',', regex=False).sum()

np.int64(1153)

In [75]:
df_clean.loc[
    df_clean['country'].str.contains(',', regex=False),
    'country'
].head(20)

11                  Poland, United States
17         Norway, Iceland, United States
48                  South Africa, Nigeria
50            United States, South Africa
54                        Portugal, Spain
68            Hong Kong, China, Singapore
71                 United States, Germany
89     South Africa, China, United States
96          United States, France, Serbia
105               Denmark, France, Poland
126           New Zealand, United Kingdom
139              Australia, United States
146                 Mexico, United States
148                  United States, China
149                      China, Hong Kong
153         United States, United Kingdom
162            France, South Korea, Japan
163                 United States, Canada
165         United Kingdom, United States
169    Netherlands, Denmark, South Africa
Name: country, dtype: str

In [76]:
(df_clean['country'] == 'Not Specified').sum()

np.int64(507)

In [84]:
df_clean['listed_in'].str.contains(',', regex=False).sum()

np.int64(5986)

In [85]:
df_clean.loc[
    df_clean['listed_in'].str.contains(',', regex=False),
    'listed_in'
].head(20)

0     International TV Shows, TV Dramas, TV Sci-Fi &...
1                          Dramas, International Movies
2                   Horror Movies, International Movies
3     Action & Adventure, Independent Movies, Sci-Fi...
5       International TV Shows, TV Dramas, TV Mysteries
6                   Horror Movies, International Movies
8                   Horror Movies, International Movies
9        Horror Movies, International Movies, Thrillers
10                                    Dramas, Thrillers
11    Crime TV Shows, International TV Shows, TV Dramas
12    Crime TV Shows, Docuseries, International TV S...
13    Documentaries, International Movies, Sports Mo...
14      Independent Movies, Sci-Fi & Fantasy, Thrillers
15              Dramas, International Movies, Thrillers
16                    International TV Shows, TV Dramas
17                                    Dramas, Thrillers
18                 Comedies, Dramas, Independent Movies
20     Dramas, Independent Movies, International Movies
21     Action & Adventure, Dramas, International Movies
22                         Dramas, International Movies
Name: listed_in, dtype: str

In [86]:
df_clean['listed_in'].isnull().sum()

np.int64(0)

In [87]:
text_columns = [
    'show_id',
    'type',
    'title',
    'director',
    'cast',
    'country',
    'rating',
    'duration',
    'listed_in',
    'description'
]

In [88]:
for col in text_columns:
    df_clean[col] = df_clean[col].str.strip()

In [89]:
print(df_clean['type'].unique())

<StringArray>
['TV Show', 'Movie']
Length: 2, dtype: str

In [90]:
print(df_clean['rating'].unique())

<StringArray>
[    'TV-MA',         'R',     'PG-13',     'TV-14',     'TV-PG',        'NR',
      'TV-G',      'TV-Y', 'Not Rated',     'TV-Y7',        'PG',         'G',
     'NC-17',  'TV-Y7-FV',        'UR']
Length: 15, dtype: str

In [91]:
print(df_clean['duration'].head())

0    4 Seasons
1       93 min
2       78 min
3       80 min
4      123 min
Name: duration, dtype: str

In [92]:
df_clean.isnull().sum()

show_id                0
type                   0
title                  0
director               0
cast                   0
country                0
date_added            10
release_year           0
rating                 0
duration               0
listed_in              0
description            0
duration_minutes    2410
duration_seasons    5377
dtype: int64

In [93]:
df_clean.shape

(7787, 14)

In [94]:
df_clean.duplicated().sum()

np.int64(0)

In [95]:
df_clean['show_id'].nunique()

7787

In [98]:
from pathlib import Path

output_path = Path.cwd().parent / "data" / "processed" / "netflix_cleaned.csv"

df_clean.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print(output_path)

Cleaned dataset saved successfully!
c:\Users\shiva\OneDrive\Desktop\Company\DynamixNetworks_Netflix_Analysis\data\processed\netflix_cleaned.csv

In [99]:
print(output_path.exists())

True